### ISSUE TITLE
Update photos in slideshow

### ISSUE THREAD

**Issue by wildlifehexagon** [dictyBase/dicty-frontpage#56]
Use photos from here: http://dictybase.org/Multimedia/index.html

And add captions

**Comment by pfey03** [comment]
Here is what you can use for now. Since I give a talk at the meeting I will shout out to send us pictures we can float on the front page. Below the link I write the caption you can add (I did formatting like SGD but feel free to change whatever looks good). Try not to change proportions of the pictures.

1) http://dictybase.org/Multimedia/LarryBlanton/dev.html
**DIcty Life Cycle** Courtesy of M.J. Grimson & R.L. Blanton, Biological Sciences Electron Microscopy Laboratory, Texas Tech University

2) http://dictybase.org/Multimedia/LarryBlanton/culm2.html It needs to stay upright; maybe make size that's possible and extend white space left and right. If it doesn't look good let it be. 
**Dictyostelium early culminant** Courtesy of M.J. Grimson & R.L. Blanton, Biological Sciences Electron Microscopy Laboratory, Texas Tech University

3) http://dictybase.org/Multimedia/Graef/Dicty_tubulin_centrosom.tif maybe you can crop off a bit black on top and bottom or fill in black background if needed
**Triple stained and fixed Dictyostelium cells: apha-tubulin (green),  centrosome (red, appears yellow due to colocalization with tubulin), nuclei (blue)** Courtesy of Ralph Gräf, Potsdam University

4) http://dictybase.org/Multimedia/MacWilliams/young-culminate.tif This picture is so nice but also needs to stay upright and has complicated background. If you can make it work would be awesome but don't spend too much time.
**Very early culminant expressing labile gal (red) and stable gus (blue) from the ecmB promoter** Courtesy the late Harry MacWilliams

**Comment by pfey03** [comment]
Ah, good news, you can keep there slug picture
https://www.google.com/imgres?imgurl=https%3A%2F%2Fucsdnews.ucsd.edu%2Farchive%2Fgraphics%2Fimages%2F2004%2Fdictyslug_lg.jpg&imgrefurl=https%3A%2F%2Fucsdnews.ucsd.edu%2Farchive%2Fnewsrel%2Fscience%2Fmcamoeba.asp&docid=vHPJWc-ovEoHyM&tbnid=eXb-Z-FZHYF6yM%3A&vet=12ahUKEwiv5JDr0rrcAhWB5oMKHWI6B6M4ZBAzKF4wXnoECAEQYQ..i&w=800&h=526&client=safari&bih=1124&biw=1813&q=Dictyostelium%20discoideum&ved=2ahUKEwiv5JDr0rrcAhWB5oMKHWI6B6M4ZBAzKF4wXnoECAEQYQ&iact=mrc&uact=8

**Dictyostelium slug** Courtesy Dirk Dormann, University of Dundee

**Comment by wildlifehexagon** [comment]
I've added the three specified images. No captions yet, however, as that will require some reconfiguring of the slideshow. Will make note of when they are added.

**Comment by pfey03** [comment]
@wildlifehexagon Do you think you can add some credits to those pics? I at least want to say at the meeting we will add those when I ask people to end more pictures

**Comment by wildlifehexagon** [comment]
I've added credits to these images in `develop`. Will make note when these changes are live on `testdb`.
